# OpenNext for Cloudflare Workers
# https://opennext.js.org/cloudflare

name = "scribe"
main = ".open-next/worker.js"
compatibility_date = "2026-02-04"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
pages_build_output_dir = ".open-next"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "scribe"

[[d1_databases]]
binding = "DB"
database_name = "scribe-db"
database_id = "c5fbbe85-21d7-42ef-8de1-00c2a68937b5"
